DROP TABLE IF EXISTS practica.tmp_geonames;
DROP TABLE IF EXISTS practica.tmp_country_codes;
DROP TABLE IF EXISTS practica.tmp_level_1a;
DROP TABLE IF EXISTS practica.tmp_locations;
DROP TABLE IF EXISTS practica.tmp_projects;
DROP TABLE IF EXISTS practica.tmp_transaction;

DROP TABLE IF EXISTS practica.TRANSACTION;
DROP TABLE IF EXISTS practica.CURRENCY;
DROP TABLE IF EXISTS practica.LEVEL_1A;
DROP TABLE IF EXISTS practica.PROJECT;
DROP TABLE IF EXISTS practica.TYPE_STATUS;
DROP TABLE IF EXISTS practica.COUNTRY_CODE;
DROP TABLE IF EXISTS practica.GEONAME;
DROP TABLE IF EXISTS practica.LOCATION;